/**
 * generated-detect.ts - 自動生成ファイル検出の pure ロジック (SSoT)
 *
 * I/O を持たず、名前規則 / .gitattributes / 先頭マーカーで生成物を分類する。
 * リモート PR 用 (mark-generated-viewed/scripts/detect-generated.ts) とローカル
 * diff 用 (_shared/detect-generated-local.ts) の双方から再利用される。
 */

// ファイル名/パス規則。先頭マーカーを持たない生成物 (lock / swagger 等) を拾う。
const NAME_RULES: { reason: string; re: RegExp }[] = [
  {
    reason: "name:lockfile",
    re: /(^|\/)(package-lock\.json|npm-shrinkwrap\.json|yarn\.lock|pnpm-lock\.yaml|bun\.lockb?|composer\.lock|Gemfile\.lock|poetry\.lock|uv\.lock|Cargo\.lock|flake\.lock|go\.sum|Pipfile\.lock|deno\.lock|Podfile\.lock|gradle\.lockfile)$/,
  },
  {
    reason: "name:protobuf",
    re: /(\.pb\.(go|cc|h)|\.pb\.gw\.go|_pb2\.pyi?|_pb2_grpc\.py|\.pb\.dart)$/,
  },
  {
    reason: "name:openapi-spec",
    re: /(^|\/)(swagger|openapi)\.(json|ya?ml)$/,
  },
  {
    reason: "name:gen-suffix",
    re: /(\.gen\.(go|ts|tsx|py)|_gen\.go|\.generated\.(ts|tsx|cs))$/,
  },
];

// より具体的なパターンを先に並べ、最初に一致した reason を返す。
const CONTENT_MARKERS: { reason: string; re: RegExp }[] = [
  { reason: "content:go-codegen", re: /Code generated .* DO NOT EDIT/ },
  { reason: "content:generated-tag", re: /@generated\b/ },
  { reason: "content:orval", re: /Generated by orval/ },
  {
    reason: "content:auto-generated",
    re: /\b(auto-?generated|automatically generated)\b/i,
  },
  { reason: "content:do-not-edit", re: /\bDO NOT EDIT\b/ },
];

// 生成マーカーはファイル先頭に出るため走査を head に限定する (余裕を見て 40 行)
const HEAD_LINES = 40;

export function classifyByName(path: string): string | null {
  for (const { reason, re } of NAME_RULES) {
    if (re.test(path)) return reason;
  }
  return null;
}

export function classifyByContent(content: string): string | null {
  // minified / 巨大ファイルでの regex コストを抑える。生成マーカーは常に先頭に出る
  const head = content.slice(0, 8192).split("\n").slice(0, HEAD_LINES).join("\n");
  for (const { reason, re } of CONTENT_MARKERS) {
    if (re.test(head)) return reason;
  }
  return null;
}

export type GitattrEntry = { re: RegExp; generated: boolean };

// common subset の glob のみ対応。変換不能なパターンは null (呼び出し側で skip = 安全側)
export function gitattrGlobToRegex(pattern: string): RegExp | null {
  let p = pattern;
  let dirOnly = false;
  if (p.endsWith("/")) {
    dirOnly = true;
    p = p.slice(0, -1);
  }
  const anchored = p.startsWith("/");
  if (anchored) p = p.slice(1);
  const hasSlash = p.includes("/");

  let re = "";
  for (let i = 0; i < p.length; i++) {
    const c = p[i];
    if (c === "*") {
      if (p[i + 1] === "*") {
        // `**/<rest>` は 0 個以上のディレクトリ。`(?:.*/)?` で / 境界を保ち、.* が継続リテラルに
        // 直結して glued name (`src/**/foo` が `src/xfoo` を) 誤マッチするのを防ぐ
        if (p[i + 2] === "/") {
          re += "(?:.*/)?";
          i += 2;
        } else {
          re += ".*";
          i++;
        }
      } else {
        re += "[^/]*";
      }
    } else if (c === "?") {
      re += "[^/]";
    } else if (".+^${}()|[]\\".includes(c)) {
      re += "\\" + c;
    } else {
      re += c;
    }
  }

  // スラッシュを含まないパターンは basename をどの階層でも一致させる (gitignore 仕様)
  const prefix = anchored || hasSlash ? "^" : "(^|/)";
  const suffix = dirOnly ? "(/|$)" : "$";
  try {
    return new RegExp(prefix + re + suffix);
  } catch {
    return null;
  }
}

export function parseGitattributes(text: string): GitattrEntry[] {
  const entries: GitattrEntry[] = [];
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const parts = line.split(/\s+/);
    const pattern = parts[0];
    let generated: boolean | null = null;
    for (const attr of parts.slice(1)) {
      if (attr === "linguist-generated" || attr === "linguist-generated=true") {
        generated = true;
      } else if (attr === "-linguist-generated" || attr === "linguist-generated=false") {
        generated = false;
      }
    }
    if (generated === null) continue;
    const re = gitattrGlobToRegex(pattern);
    if (re) entries.push({ re, generated });
  }
  return entries;
}

// gitattributes は後勝ち (最後に一致した行の値が有効)。
export function gitattributesGenerated(path: string, entries: GitattrEntry[]): boolean {
  let result = false;
  for (const e of entries) {
    if (e.re.test(path)) result = e.generated;
  }
  return result;
}
